/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Login.java
 *
 * Created on 22-dic-2011, 20:31:26
 */

package Utilidades;

import Controlador.EmpleadosJpaController;
import Modelo.Empleados;
import javax.persistence.Query;
import javax.swing.JOptionPane;

/**
 * Esta clase es la encargada de mostrar el dialogo de inicio de sesion y realizara la validacion del usuario
 * @author JuanPaulo
 */
public class Login extends javax.swing.JDialog {

    private Empleados empleado; // variable que almacenara un usuario de la BD
    private boolean salir;// varaiable que se utilizara para saber si se tiene que salir o no del sistema, si es true
    // es porque hay que salir del sistema en caso contrario no

    Query consultaEmpleado;
    EmpleadosJpaController controladorEmpleados;
    /** Creates new form Login */

    public Login(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controladorEmpleados = new EmpleadosJpaController();
        consultaEmpleado= controladorEmpleados.getEm().createQuery("SELECT e FROM Empleados e WHERE e.usuario.usuario = :usuario");
        salir=false;
        Utilidades.centrar(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        tfUsuario = new javax.swing.JTextField();
        tfPass = new javax.swing.JPasswordField();
        lbIcono = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        lbPass = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        btAceptar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acceso al sistema");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout(10, 10));

        jPanel2.setLayout(new java.awt.GridLayout(1, 2, 0, 5));

        jPanel4.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.insets = new java.awt.Insets(4, 29, 4, 29);
        jPanel4.add(tfUsuario, gridBagConstraints);

        tfPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPassActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.insets = new java.awt.Insets(4, 29, 4, 29);
        jPanel4.add(tfPass, gridBagConstraints);

        lbIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/candado.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.insets = new java.awt.Insets(1, 29, 0, 1);
        jPanel4.add(lbIcono, gridBagConstraints);

        lbUsuario.setText("Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        jPanel4.add(lbUsuario, gridBagConstraints);

        lbPass.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        jPanel4.add(lbPass, gridBagConstraints);

        jPanel2.add(jPanel4);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        lbTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/keys.gif"))); // NOI18N
        lbTitulo.setText("Acceso al sistema");
        jPanel6.add(lbTitulo);

        jPanel3.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));
        jPanel7.add(jSeparator1);

        jPanel3.add(jPanel7);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        btAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/Aceptar.png"))); // NOI18N
        btAceptar.setText("Aceptar");
        btAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceptarActionPerformed(evt);
            }
        });
        jPanel5.add(btAceptar);

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/Cancelar.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        jPanel5.add(btCancelar);

        jPanel1.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPassActionPerformed
        // TODO add your handling code here:
        setSalir(false);
        this.Validar();
}//GEN-LAST:event_tfPassActionPerformed

    private void btAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceptarActionPerformed
        // TODO add your handling code here:
        setSalir(false);
        this.Validar();
    }//GEN-LAST:event_btAceptarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        setSalir(true);
        this.setVisible(false);
}//GEN-LAST:event_btCancelarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        setSalir(true);
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing


    /**
     * metodo que servira para validar un usuario en el sistema
     */
    private void Validar(){
        String nombreUsuario= tfUsuario.getText();
        String pass = new String(tfPass.getPassword());
        /**JPA maneja todas las operaciones CRUD(Create, Read, Update, Delete - Crear, Leer, Actualizar, Borrar)
         * a través de la interface EntityManager.
         */
        if(!nombreUsuario.equals("")){
            /** Se busca el usuario con el nombre de usuario del campo usuario a travez del metodo find del entitymanager
             */
            consultaEmpleado.setParameter("usuario", nombreUsuario);
            //setEmpleado(setUsuario(entityManager1.find(Usuarios.class, nombreUsuario)));
             /** Si se encuantra el usuario se accedera al menu principal, en caso contrario se saldra del sistema*/

            try{
                empleado = (Empleados) consultaEmpleado.getSingleResult();
            }catch(javax.persistence.NoResultException e){
                System.out.println("prueba");
            }
            
             if(empleado!=null){
                 if(empleado.getUsuario().getPassword().equals(pass)){
                     this.setVisible(false);
                 }else{
                     JOptionPane.showMessageDialog(this, "El usuario o password es incorrecto", "Atencion", (int) CENTER_ALIGNMENT);
                     tfPass.setText("");

                 }
             }else{
                 JOptionPane.showMessageDialog(this, "El usuario o password es incorrecto", "Atencion", WIDTH);
                 tfPass.setText("");
             }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAceptar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbIcono;
    private javax.swing.JLabel lbPass;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JPasswordField tfPass;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the salir
     */
    public boolean isSalir() {
        return salir;
    }

    /**
     * @param salir the salir to set
     */
    public void setSalir(boolean salir) {
        this.salir = salir;
    }

    /**
     * @return the empleado
     */
    public Empleados getEmpleado() {
        return empleado;
    }

    /**
     * @param empleado the empleado to set
     */
    public void setEmpleado(Empleados empleado) {
        this.empleado = empleado;
    }

}
