/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * buscarEmpleados.java
 *
 * Created on 31-ene-2012, 15:01:13
 */

package Vistas.Emplados;

import javax.swing.JOptionPane;

/**
 *
 * @author weejdu01
 */
public class buscarEmpleados extends javax.swing.JDialog {

    private int id;// contendra el id a buscar
    private String dni;// contendra el dni a buscar
    private String apellidos;// contendra el apellido a buscar
    private int seleccionBusqueda; // contendra el tipo de busqueda ( si es 0 se listaran todas los empleados. si es 1 se filtrara por id, 2 si es por dny y 3 si es por apellidos,4 no hara nada)
    private boolean cerrar;// variable para saber si hay que cerrar la ventana o no(true = si, false =no)

    /** Creates new form buscarEmpleados */
    public buscarEmpleados(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        seleccionBusqueda=0;
        cerrar=false;
        Utilidades.Utilidades.centrar(this);
    }

    /**
     * metodo que modificara la variable seleccionBusqueda segun la opcion seleccionada
     */
    private void seleccionBusqueda(){
        if(tfBuscar.getText().equals("")){
            seleccionBusqueda=0;
            cerrar=true;
        }else{
            if(jRBId.isSelected()){
                try{
                    id= Integer.parseInt(tfBuscar.getText());
                    seleccionBusqueda=1;
                    cerrar=true;
                }catch(NumberFormatException nfe){
                    cerrar=false;
                    JOptionPane.showMessageDialog(this, "El id debe ser un valor numerico", "Atencion",JOptionPane.WARNING_MESSAGE);   
                }            
            }

            if(jRBDni.isSelected()){
                dni=tfBuscar.getText();
                seleccionBusqueda=2;
                cerrar=true;
            }

            if(jRBApellidos.isSelected()){
                apellidos=tfBuscar.getText();
                seleccionBusqueda=3;
                cerrar=true;
            }
        }
    }

    /**
     * @return the id
     */
    public int getId() {
        return id;
    }

    /**
     * @return the dni
     */
    public String getDni() {
        return dni;
    }

    /**
     * @return the Apellidos
     */
    public String getApellidos() {
        return apellidos;
    }

    /**
     * @return the seleccionBusqueda
     */
    public int getSeleccionBusqueda() {
        return seleccionBusqueda;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        tfBuscar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jRBId = new javax.swing.JRadioButton();
        jRBDni = new javax.swing.JRadioButton();
        jRBApellidos = new javax.swing.JRadioButton();
        btBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Busqueda de Empleados");
        setBackground(java.awt.Color.white);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setName("jPanel1"); // NOI18N

        lbTitulo.setFont(new java.awt.Font("Tahoma", 1, 18));
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/Buscar2.png"))); // NOI18N
        lbTitulo.setText("Buscar Empleado");
        lbTitulo.setName("lbTitulo"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        jLabel1.setText("Buscar");
        jLabel1.setName("jLabel1"); // NOI18N

        tfBuscar.setName("tfBuscar"); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar por"));
        jPanel2.setName("jPanel2"); // NOI18N

        buttonGroup1.add(jRBId);
        jRBId.setSelected(true);
        jRBId.setText("Numero de Empleado");
        jRBId.setName("jRBId"); // NOI18N

        buttonGroup1.add(jRBDni);
        jRBDni.setText("Dni");
        jRBDni.setName("jRBDni"); // NOI18N

        buttonGroup1.add(jRBApellidos);
        jRBApellidos.setText("Apellidos");
        jRBApellidos.setName("jRBApellidos"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBId)
                    .addComponent(jRBDni)
                    .addComponent(jRBApellidos))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRBId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRBDni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRBApellidos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btBuscar.setText("Buscar");
        btBuscar.setName("btBuscar"); // NOI18N
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 8));
        jLabel3.setText("Nota:Si se deja en balnco el campo buscar se buscaran todos los empleados");
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(10, 10, 10)
                                        .addComponent(tfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btBuscar))
                                .addGap(40, 40, 40)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel3))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel1))
                            .addComponent(tfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btBuscar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:

        seleccionBusqueda=4;
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        // TODO add your handling code here:
        seleccionBusqueda();
        if(cerrar){
          this.setVisible(false);
        }
        
    }//GEN-LAST:event_btBuscarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                buscarEmpleados dialog = new buscarEmpleados(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRBApellidos;
    private javax.swing.JRadioButton jRBDni;
    private javax.swing.JRadioButton jRBId;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField tfBuscar;
    // End of variables declaration//GEN-END:variables

}
