/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * totalDiaVentas.java
 *
 * Created on 23-feb-2012, 11:42:48
 */

package Vistas.Facturacion;

import Controlador.CompraJpaController;
import Controlador.ReparacionesJpaController;
import Modelo.Compra;
import Modelo.Reparaciones;
import java.text.NumberFormat;
import java.util.Calendar;
import java.util.List;
import javax.persistence.Query;

/**
 *
 * @author weejdu01
 */
public class totalMesVentas extends javax.swing.JDialog {
    private CompraJpaController controladorCompras; //controlador que gestionara las transacciones y las operacion sdobre el entityManager
    private ReparacionesJpaController  controladorReparaciones; // controlador que gestionara las transacciones y la persistencia de datos
    private Query consultaCompras; // consulta que se utilizara para obtener la lista de compras
    private Query consultaReparaciones; // consulta que se utilizara para obtener la lista de reparaciones
    private float totalCompras; // contendra el total de todas las compras
    private float totalReparaciones; // contendra el total de las reparaciones
    /** Creates new form totalDiaVentas */
    public totalMesVentas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controladorCompras= new CompraJpaController();
        consultaCompras = controladorCompras.getEm().createQuery("SELECT c FROM Compra c WHERE c.fecha>=:fecha");
        controladorReparaciones= new ReparacionesJpaController();
        consultaReparaciones = controladorReparaciones.getEm().createQuery("SELECT r FROM Reparaciones r WHERE r.estado='facturado'AND r.fechaSal>=:fecha");
        calcularTotalCompras();
        calcularTotalReparaciones();
        totalVentas();
        Utilidades.Utilidades.centrar(this);
    }
    /**
     * Metodo que pasa la fecha a string
     * @param mes
     * @param ano
     */
    private void fechaString(int mes, int ano){
        int m=mes;
        int a=ano;
        String ms = Utilidades.UtilidadesComprobar.mesString(m);
        String as= String.valueOf(a);
        String fecha= ms+"-"+as;
        jLabel11.setText(fecha);

    }
    /**
     * metodo que calcula el total de las compras del mes
     */
    private void calcularTotalCompras(){
        Calendar ahoraCal = Calendar.getInstance();
        int ano = ahoraCal.get(Calendar.YEAR);
        int mes = ahoraCal.get(Calendar.MONTH);
        fechaString(mes,ano);
        NumberFormat formateadorNumerico=NumberFormat.getInstance();
        formateadorNumerico.setMaximumFractionDigits(2);
        ahoraCal.set(ano, mes, 1);
        java.util.Date fecha =ahoraCal.getTime();
        consultaCompras.setParameter("fecha", fecha);
        List<Compra> compras =consultaCompras.getResultList();
        totalCompras=0;
        if(compras!=null){
            for(int i=0;i<compras.size();i++){
                totalCompras+=compras.get(i).getTotalCompraIva();
            }
            jLabel2.setText(formateadorNumerico.format(totalCompras));
        }
        System.out.println(fecha);
    }
    /**
     * metodo que calcula el total de las reparaciones del mes
     */
    private void calcularTotalReparaciones(){
        Calendar ahoraCal = Calendar.getInstance();
        int ano = ahoraCal.get(Calendar.YEAR);
        int mes = ahoraCal.get(Calendar.MONTH);

        NumberFormat formateadorNumerico=NumberFormat.getInstance();
        formateadorNumerico.setMaximumFractionDigits(2);
        ahoraCal.set(ano, mes, 1);
        java.util.Date fecha =ahoraCal.getTime();

        consultaReparaciones.setParameter("fecha", fecha);
        List<Reparaciones> reparaciones = consultaReparaciones.getResultList();
        totalReparaciones=0;
        if(reparaciones!=null){
            for(int i=0;i<reparaciones.size();i++){
                totalReparaciones+=reparaciones.get(i).getTotalReparacionIva();
            }
            jLabel4.setText(formateadorNumerico.format(totalReparaciones));
        }
    }

    /**
     * metodo que calcula el total de las ventas (compras + reparaciones facturadas)
     */
    private void totalVentas(){
        NumberFormat formateadorNumerico=NumberFormat.getInstance();
        formateadorNumerico.setMaximumFractionDigits(2);
        float total=totalCompras + totalReparaciones;
        jLabel6.setText(formateadorNumerico.format(total));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Facturacion del mes");
        setResizable(false);

        lbTitulo.setFont(new java.awt.Font("Tahoma 18 Negrita 18 Negrita", 1, 18));
        lbTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/factura.png"))); // NOI18N
        lbTitulo.setText("Facturacion del Mes");
        lbTitulo.setName("lbTitulo"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Total Compras:");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("jLabel2");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setText("Total Reparaciones:");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel4.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4.setText("jLabel4");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel5.setText("Total:");
        jLabel5.setName("jLabel5"); // NOI18N

        jSeparator2.setName("jSeparator2"); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel6.setForeground(new java.awt.Color(204, 0, 51));
        jLabel6.setText("jLabel6");
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setText("€");
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel8.setText("€");
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel9.setText("€");
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel10.setText("Fecha:");
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel11.setText("jLabel11");
        jLabel11.setName("jLabel11"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lbTitulo)
                .addContainerGap(55, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addGap(13, 13, 13)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                totalMesVentas dialog = new totalMesVentas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbTitulo;
    // End of variables declaration//GEN-END:variables

}
